# Etapa 1: Build Angular
FROM node:21 AS builder
WORKDIR /app
COPY sockets-test/ ./
RUN npm install
RUN npm run build --prod

# Etapa 2: Servir con Nginx
FROM nginx:alpine
COPY --from=builder /app/dist/sockets-test/browser /usr/share/nginx/html
EXPOSE 80